name: Build and Publish NuGet Packages for gstreamer-netcore-ges

on:
  push:
    branches:
      - mingw-ges  # Run only on pushes to the mingw-ges branch
  pull_request:
    branches:
      - mingw-ges

jobs:
  build:
    runs-on: windows-latest  # Use Windows, as specified

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize and update submodules
        run: |
          git submodule init
          git submodule update

      # Step 2: Setup .NET Core
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'  # Target netcoreapp3.1

      # Step 3: Restore dependencies for both projects
      - name: Restore dependencies for gstreamer-sharp-netcore
        run: dotnet restore gstreamer-sharp-netcore.csproj

      - name: Restore dependencies for gstreamer-sharp-ges-netcore
        run: dotnet restore gstreamer-sharp-ges-netcore.csproj

      # Step 4: Build both projects in Release mode
      - name: Build gstreamer-sharp-netcore
        run: dotnet build gstreamer-sharp-netcore.csproj --configuration Release

      - name: Build gstreamer-sharp-ges-netcore
        run: dotnet build gstreamer-sharp-ges-netcore.csproj --configuration Release

      # Step 5: Pack both projects into NuGet packages
      - name: Pack gstreamer-sharp-netcore
        run: dotnet pack gstreamer-sharp-netcore.csproj --configuration Release --output ./nupkg

      - name: Pack gstreamer-sharp-ges-netcore
        run: dotnet pack gstreamer-sharp-ges-netcore.csproj --configuration Release --output ./nupkg

      # Step 6: Publish both packages to NuGet (optional, requires secret key)
      - name: Publish gstreamer-sharp-netcore to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}  # Store your API key in GitHub Secrets
        run: dotnet nuget push .\nupkg\gstreamer-sharp-netcore.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Publish gstreamer-sharp-ges-netcore to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}  # Store your API key in GitHub Secrets
        run: dotnet nuget push .\nupkg\gstreamer-sharp-ges-netcore.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
